### ISSUE TITLE
Unable to install the app

### ISSUE THREAD

**Issue by sagorahmed** [batyrf/RelaxingSounds#23]
**Expected behavior**
I expected that I could install the app after downloading it from Github smoothly.

**Actual behavior**
When I am trying to install the "Relaxing Sounds" app it shows "App not Installed"

**How to reproduce**

> Download the app

> When the Downloading process end, try to install it and notice it.

**Information**
Operating system: Android 10, Android 7
Devices: Samsung A5 and A6+, Xiaomi Mi A3

**Recording Of The Bug**

![20201208_122927](https://user-images.githubusercontent.com/33980813/101449130-6afd0380-3952-11eb-8d21-3f64c1e6583c.gif)

**Comment by batyrf** [comment]
Thank you for notifying. Must be fixed now

**Comment by sagorahmed** [comment]
Thanks for fixing the issue...
